### ISSUE TITLE
Retro Day 1: what can be improved?

### ISSUE THREAD

**Issue by asalbers** [aa-demo-org/ActionsFundamentals-March-26-28#4]

**Comment by jasonheath** [comment]
The optional steps on "my first action" might be out of date.

**Comment by sean-simmons-progress** [comment]
Might change the instructions so that you can work inside a dev branch, vs off main. Just updating the 
```
on:
  push:
    branches: 
       - 'main'
       - 'dev'
 ```

something of the sort.
